# Generated by Django 4.2.16 on 2025-06-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='access_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
