# Generated by Django 5.0.6 on 2024-08-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_alter_driver_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='hire_date',
            field=models.DateField(blank=True),
        ),
    ]
