# Generated by Django 4.2.16 on 2025-06-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driverresponse_driver_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='access_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
