# Generated by Django 5.0.6 on 2024-08-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_alter_driver_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='media/profile_pics'),
        ),
    ]
