# Generated by Django 4.2.16 on 2025-06-07 15:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_alter_driver_access_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverStartingShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField()),
                ('load', models.PositiveIntegerField()),
                ('mileage', models.PositiveIntegerField()),
                ('delivery_areas', models.JSONField(default=list)),
                ('status', models.BooleanField(default=True)),
                ('absence_type', models.CharField(blank=True, choices=[('MAINTENANCE', 'Maintenance'), ('SICKNESS', 'Sickness'), ('OTHER', 'Other')], max_length=100, null=True)),
                ('absence_description', models.TextField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='drivers.driver')),
            ],
        ),
        migrations.DeleteModel(
            name='DriverResponse',
        ),
    ]
