# Generated by Django 5.0.6 on 2024-08-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_alter_driver_email_alter_driver_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
