# Generated by Django 5.0.6 on 2024-08-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_alter_driver_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
