# Generated by Django 5.0.6 on 2024-08-19 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_alter_driver_address_alter_driver_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='licence_expiry_date',
            new_name='license_expiry_date',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='licence_number',
            new_name='license_number',
        ),
    ]
