# Generated by Django 4.2.16 on 2025-05-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancereport',
            name='part_counter',
            field=models.JSONField(default=dict),
        ),
    ]
