# Generated by Django 5.0.6 on 2024-09-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancereport',
            name='maintenance_type',
            field=models.CharField(choices=[('PREVENTIVE', 'Preventive'), ('CURATIVE', 'Curative')], default='PREVENTIVE', max_length=50),
        ),
    ]
