# Generated by Django 4.2.16 on 2024-11-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_maintenancereport_maintenance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancereport',
            name='parts',
            field=models.ManyToManyField(blank=True, related_name='maintenance_reports', to='maintenance.partpurchaseevent'),
        ),
    ]
