# Generated by Django 4.2.16 on 2025-05-04 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_maintenancereport_part_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancereport',
            name='part_counter',
        ),
    ]
