# Generated by Django 4.2.16 on 2025-04-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_partpurchaseevent_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
