# Generated by Django 4.2.16 on 2025-04-28 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('maintenance', '0003_alter_part_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='partsprovider',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts_providers', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_providers', to='accounts.userprofile'),
        ),
    ]
