# Generated by Django 4.2.16 on 2025-04-30 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_part_profile_partsprovider_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partpurchaseevent',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_purchase_events', to='maintenance.part'),
        ),
        migrations.AlterField(
            model_name='partpurchaseevent',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_purchase_events', to='maintenance.partsprovider'),
        ),
        migrations.AlterField(
            model_name='serviceproviderevent',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider_events', to='maintenance.serviceprovider'),
        ),
    ]
